vlog -work work D:/prj/ca/5/simulation/modelsim/Waveform.vwf.vt
vsim -novopt -c -t 1ps -L cycloneiv_ver -L altera_ver -L altera_mf_ver -L 220model_ver -L sgate work.ca5_vlg_vec_tst
onerror {resume}
add wave {ca5_vlg_vec_tst/i1/A}
add wave {ca5_vlg_vec_tst/i1/A[31]}
add wave {ca5_vlg_vec_tst/i1/A[30]}
add wave {ca5_vlg_vec_tst/i1/A[29]}
add wave {ca5_vlg_vec_tst/i1/A[28]}
add wave {ca5_vlg_vec_tst/i1/A[27]}
add wave {ca5_vlg_vec_tst/i1/A[26]}
add wave {ca5_vlg_vec_tst/i1/A[25]}
add wave {ca5_vlg_vec_tst/i1/A[24]}
add wave {ca5_vlg_vec_tst/i1/A[23]}
add wave {ca5_vlg_vec_tst/i1/A[22]}
add wave {ca5_vlg_vec_tst/i1/A[21]}
add wave {ca5_vlg_vec_tst/i1/A[20]}
add wave {ca5_vlg_vec_tst/i1/A[19]}
add wave {ca5_vlg_vec_tst/i1/A[18]}
add wave {ca5_vlg_vec_tst/i1/A[17]}
add wave {ca5_vlg_vec_tst/i1/A[16]}
add wave {ca5_vlg_vec_tst/i1/A[15]}
add wave {ca5_vlg_vec_tst/i1/A[14]}
add wave {ca5_vlg_vec_tst/i1/A[13]}
add wave {ca5_vlg_vec_tst/i1/A[12]}
add wave {ca5_vlg_vec_tst/i1/A[11]}
add wave {ca5_vlg_vec_tst/i1/A[10]}
add wave {ca5_vlg_vec_tst/i1/A[9]}
add wave {ca5_vlg_vec_tst/i1/A[8]}
add wave {ca5_vlg_vec_tst/i1/A[7]}
add wave {ca5_vlg_vec_tst/i1/A[6]}
add wave {ca5_vlg_vec_tst/i1/A[5]}
add wave {ca5_vlg_vec_tst/i1/A[4]}
add wave {ca5_vlg_vec_tst/i1/A[3]}
add wave {ca5_vlg_vec_tst/i1/A[2]}
add wave {ca5_vlg_vec_tst/i1/A[1]}
add wave {ca5_vlg_vec_tst/i1/A[0]}
add wave {ca5_vlg_vec_tst/i1/B}
add wave {ca5_vlg_vec_tst/i1/B[31]}
add wave {ca5_vlg_vec_tst/i1/B[30]}
add wave {ca5_vlg_vec_tst/i1/B[29]}
add wave {ca5_vlg_vec_tst/i1/B[28]}
add wave {ca5_vlg_vec_tst/i1/B[27]}
add wave {ca5_vlg_vec_tst/i1/B[26]}
add wave {ca5_vlg_vec_tst/i1/B[25]}
add wave {ca5_vlg_vec_tst/i1/B[24]}
add wave {ca5_vlg_vec_tst/i1/B[23]}
add wave {ca5_vlg_vec_tst/i1/B[22]}
add wave {ca5_vlg_vec_tst/i1/B[21]}
add wave {ca5_vlg_vec_tst/i1/B[20]}
add wave {ca5_vlg_vec_tst/i1/B[19]}
add wave {ca5_vlg_vec_tst/i1/B[18]}
add wave {ca5_vlg_vec_tst/i1/B[17]}
add wave {ca5_vlg_vec_tst/i1/B[16]}
add wave {ca5_vlg_vec_tst/i1/B[15]}
add wave {ca5_vlg_vec_tst/i1/B[14]}
add wave {ca5_vlg_vec_tst/i1/B[13]}
add wave {ca5_vlg_vec_tst/i1/B[12]}
add wave {ca5_vlg_vec_tst/i1/B[11]}
add wave {ca5_vlg_vec_tst/i1/B[10]}
add wave {ca5_vlg_vec_tst/i1/B[9]}
add wave {ca5_vlg_vec_tst/i1/B[8]}
add wave {ca5_vlg_vec_tst/i1/B[7]}
add wave {ca5_vlg_vec_tst/i1/B[6]}
add wave {ca5_vlg_vec_tst/i1/B[5]}
add wave {ca5_vlg_vec_tst/i1/B[4]}
add wave {ca5_vlg_vec_tst/i1/B[3]}
add wave {ca5_vlg_vec_tst/i1/B[2]}
add wave {ca5_vlg_vec_tst/i1/B[1]}
add wave {ca5_vlg_vec_tst/i1/B[0]}
add wave {ca5_vlg_vec_tst/i1/GRD}
add wave {ca5_vlg_vec_tst/i1/GRD[31]}
add wave {ca5_vlg_vec_tst/i1/GRD[30]}
add wave {ca5_vlg_vec_tst/i1/GRD[29]}
add wave {ca5_vlg_vec_tst/i1/GRD[28]}
add wave {ca5_vlg_vec_tst/i1/GRD[27]}
add wave {ca5_vlg_vec_tst/i1/GRD[26]}
add wave {ca5_vlg_vec_tst/i1/GRD[25]}
add wave {ca5_vlg_vec_tst/i1/GRD[24]}
add wave {ca5_vlg_vec_tst/i1/GRD[23]}
add wave {ca5_vlg_vec_tst/i1/GRD[22]}
add wave {ca5_vlg_vec_tst/i1/GRD[21]}
add wave {ca5_vlg_vec_tst/i1/GRD[20]}
add wave {ca5_vlg_vec_tst/i1/GRD[19]}
add wave {ca5_vlg_vec_tst/i1/GRD[18]}
add wave {ca5_vlg_vec_tst/i1/GRD[17]}
add wave {ca5_vlg_vec_tst/i1/GRD[16]}
add wave {ca5_vlg_vec_tst/i1/GRD[15]}
add wave {ca5_vlg_vec_tst/i1/GRD[14]}
add wave {ca5_vlg_vec_tst/i1/GRD[13]}
add wave {ca5_vlg_vec_tst/i1/GRD[12]}
add wave {ca5_vlg_vec_tst/i1/GRD[11]}
add wave {ca5_vlg_vec_tst/i1/GRD[10]}
add wave {ca5_vlg_vec_tst/i1/GRD[9]}
add wave {ca5_vlg_vec_tst/i1/GRD[8]}
add wave {ca5_vlg_vec_tst/i1/GRD[7]}
add wave {ca5_vlg_vec_tst/i1/GRD[6]}
add wave {ca5_vlg_vec_tst/i1/GRD[5]}
add wave {ca5_vlg_vec_tst/i1/GRD[4]}
add wave {ca5_vlg_vec_tst/i1/GRD[3]}
add wave {ca5_vlg_vec_tst/i1/GRD[2]}
add wave {ca5_vlg_vec_tst/i1/GRD[1]}
add wave {ca5_vlg_vec_tst/i1/GRD[0]}
add wave {ca5_vlg_vec_tst/i1/CLK}
add wave {ca5_vlg_vec_tst/i1/C}
add wave {ca5_vlg_vec_tst/i1/C[2]}
add wave {ca5_vlg_vec_tst/i1/C[1]}
add wave {ca5_vlg_vec_tst/i1/C[0]}
add wave {ca5_vlg_vec_tst/i1/OUT}
add wave {ca5_vlg_vec_tst/i1/OUT[31]}
add wave {ca5_vlg_vec_tst/i1/OUT[30]}
add wave {ca5_vlg_vec_tst/i1/OUT[29]}
add wave {ca5_vlg_vec_tst/i1/OUT[28]}
add wave {ca5_vlg_vec_tst/i1/OUT[27]}
add wave {ca5_vlg_vec_tst/i1/OUT[26]}
add wave {ca5_vlg_vec_tst/i1/OUT[25]}
add wave {ca5_vlg_vec_tst/i1/OUT[24]}
add wave {ca5_vlg_vec_tst/i1/OUT[23]}
add wave {ca5_vlg_vec_tst/i1/OUT[22]}
add wave {ca5_vlg_vec_tst/i1/OUT[21]}
add wave {ca5_vlg_vec_tst/i1/OUT[20]}
add wave {ca5_vlg_vec_tst/i1/OUT[19]}
add wave {ca5_vlg_vec_tst/i1/OUT[18]}
add wave {ca5_vlg_vec_tst/i1/OUT[17]}
add wave {ca5_vlg_vec_tst/i1/OUT[16]}
add wave {ca5_vlg_vec_tst/i1/OUT[15]}
add wave {ca5_vlg_vec_tst/i1/OUT[14]}
add wave {ca5_vlg_vec_tst/i1/OUT[13]}
add wave {ca5_vlg_vec_tst/i1/OUT[12]}
add wave {ca5_vlg_vec_tst/i1/OUT[11]}
add wave {ca5_vlg_vec_tst/i1/OUT[10]}
add wave {ca5_vlg_vec_tst/i1/OUT[9]}
add wave {ca5_vlg_vec_tst/i1/OUT[8]}
add wave {ca5_vlg_vec_tst/i1/OUT[7]}
add wave {ca5_vlg_vec_tst/i1/OUT[6]}
add wave {ca5_vlg_vec_tst/i1/OUT[5]}
add wave {ca5_vlg_vec_tst/i1/OUT[4]}
add wave {ca5_vlg_vec_tst/i1/OUT[3]}
add wave {ca5_vlg_vec_tst/i1/OUT[2]}
add wave {ca5_vlg_vec_tst/i1/OUT[1]}
add wave {ca5_vlg_vec_tst/i1/OUT[0]}
add wave {ca5_vlg_vec_tst/i1/OVERFLOW}
add wave {ca5_vlg_vec_tst/i1/ZERO}
run -all
